In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as po
from sklearn.cluster import KMeans, DBSCAN
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA

import json
import warnings
import urllib.request

pd.set_option('display.max_rows', 999)
warnings.filterwarnings('ignore')

In [ ]:
data = pd.read_csv('rawdata.csv')

In [ ]:
data

TEAM W/L  MIN  PTS  FGM  FGA   FG%  ...  DREB  REB  AST  STL  BLK  TOV  PF
0     MIN   W  265  112   42   89  47.2  ...    32   40   24   10    2    8  19
1     LAL   W  240  115   42   88  47.7  ...    39   49   25    8    6   17  23
2     NYK   W  239  110   43   85  50.6  ...    31   39   30   10    3   15  22
3     DET   W  240  119   47   89  52.8  ...    40   47   27   12    4   11  21
4     BOS   W  240  110   46  102  45.1  ...    42   62   22    6    6   13  14
...   ...  ..  ...  ...  ...  ...   ...  ...   ...  ...  ...  ...  ...  ...  ..
1225  MIL   W  238  108   38   76  50.0  ...    39   45   19    6    4   15  22
1226  DET   W  239  102   41   96  42.7  ...    38   47   24   14    3    8  21
1227  IND   W  240  140   53  102  52.0  ...    33   47   29   12    9   14  25
1228  CLE   W  239  102   38   83  45.8  ...    41   50   19    3    4   17  25
1229  HOU   W  239  122   47   97  48.5  ...    33   43   28    9    5   12  16

[1230 rows x 21 columns]

In [ ]:
win = data[data['W/L']=='W']

In [ ]:
win

TEAM W/L  MIN  PTS  FGM  FGA   FG%  ...  DREB  REB  AST  STL  BLK  TOV  PF
0     MIN   W  265  112   42   89  47.2  ...    32   40   24   10    2    8  19
1     LAL   W  240  115   42   88  47.7  ...    39   49   25    8    6   17  23
2     NYK   W  239  110   43   85  50.6  ...    31   39   30   10    3   15  22
3     DET   W  240  119   47   89  52.8  ...    40   47   27   12    4   11  21
4     BOS   W  240  110   46  102  45.1  ...    42   62   22    6    6   13  14
...   ...  ..  ...  ...  ...  ...   ...  ...   ...  ...  ...  ...  ...  ...  ..
1225  MIL   W  238  108   38   76  50.0  ...    39   45   19    6    4   15  22
1226  DET   W  239  102   41   96  42.7  ...    38   47   24   14    3    8  21
1227  IND   W  240  140   53  102  52.0  ...    33   47   29   12    9   14  25
1228  CLE   W  239  102   38   83  45.8  ...    41   50   19    3    4   17  25
1229  HOU   W  239  122   47   97  48.5  ...    33   43   28    9    5   12  16

[1230 rows x 21 columns]

In [ ]:
win = win.drop(columns=['TEAM','W/L'])

In [ ]:
win

MIN  PTS  FGM  FGA   FG%  3PM  3PA  ...  DREB  REB  AST  STL  BLK  TOV  PF
0     265  112   42   89  47.2    9   23  ...    32   40   24   10    2    8  19
1     240  115   42   88  47.7   17   39  ...    39   49   25    8    6   17  23
2     239  110   43   85  50.6   12   27  ...    31   39   30   10    3   15  22
3     240  119   47   89  52.8   15   35  ...    40   47   27   12    4   11  21
4     240  110   46  102  45.1    6   24  ...    42   62   22    6    6   13  14
...   ...  ...  ...  ...   ...  ...  ...  ...   ...  ...  ...  ...  ...  ...  ..
1225  238  108   38   76  50.0    7   21  ...    39   45   19    6    4   15  22
1226  239  102   41   96  42.7    9   26  ...    38   47   24   14    3    8  21
1227  240  140   53  102  52.0    9   34  ...    33   47   29   12    9   14  25
1228  239  102   38   83  45.8    5   22  ...    41   50   19    3    4   17  25
1229  239  122   47   97  48.5   15   41  ...    33   43   28    9    5   12  16

[1230 rows x 19 columns]

In [ ]:
scaler = MinMaxScaler()

In [ ]:
scaler.fit(win)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [ ]:
scaled = scaler.transform(win)

In [ ]:
pca = PCA(n_components=4)

In [ ]:
pca.fit(scaled)

PCA(copy=True, iterated_power='auto', n_components=4, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
prcomp = pca.transform(scaled)

In [ ]:
prcomp = pd.DataFrame(data=prcomp)

In [ ]:
prcomp.head()

0         1         2         3
0 -0.002307 -0.141044 -0.042003 -0.306054
1  0.151990  0.203490  0.000063  0.300078
2  0.205637 -0.165189 -0.121042 -0.045700
3  0.356394  0.124399 -0.146324  0.005146
4 -0.319656  0.683557 -0.059847 -0.256313

In [ ]:
fig = px.scatter(prcomp,x=0, y=1)
fig.show()

In [ ]:
pca.singular_values_

array([10.19425584,  8.69399879,  7.36378258,  7.07284581])

In [ ]:
pca.components_.T

array([[ 1.39791765e-02,  8.19959830e-02,  7.70699682e-02,
        -2.37140904e-02],
       [ 4.46510943e-01,  1.07374984e-01,  3.85193165e-01,
        -1.11632640e-01],
       [ 4.13166793e-01,  1.81122798e-01,  7.47979545e-02,
        -2.54162827e-01],
       [ 7.60763247e-02,  4.87537123e-01, -2.89454751e-02,
        -3.03758061e-01],
       [ 3.98297051e-01, -1.81930977e-01,  1.05746306e-01,
        -4.51437962e-02],
       [ 3.43274556e-01,  9.90072872e-02, -1.04562713e-01,
         3.91241314e-01],
       [ 1.46471242e-01,  2.28894052e-01, -1.28427229e-01,
         3.30768128e-01],
       [ 3.15081905e-01, -1.03978840e-01, -1.34382656e-02,
         2.07300476e-01],
       [-1.32869456e-01, -1.72241318e-01,  5.66385726e-01,
         2.93726988e-04],
       [-1.11061971e-01, -1.15686663e-01,  4.25008691e-01,
        -7.49620642e-03],
       [ 1.30046630e-02, -5.43359727e-02,  9.25124367e-02,
         2.82193074e-02],
       [-1.77307574e-01,  4.26249840e-01,  1.45973379e-01,
      

In [ ]:
pca_res = pd.DataFrame(data = pca.components_.T, index=win.columns)

In [ ]:
# PCA1: 득점률 : PTS, FGM, 3PM
# PCA2: 적극성 : REB, FGA
# PCA3: 수비기술 : PF, FTM
# PCA4: 3점슛 : 3PM, 3PA 
pca_res

0         1         2         3
MIN   0.013979  0.081996  0.077070 -0.023714
PTS   0.446511  0.107375  0.385193 -0.111633
FGM   0.413167  0.181123  0.074798 -0.254163
FGA   0.076076  0.487537 -0.028945 -0.303758
FG%   0.398297 -0.181931  0.105746 -0.045144
3PM   0.343275  0.099007 -0.104563  0.391241
3PA   0.146471  0.228894 -0.128427  0.330768
3P%   0.315082 -0.103979 -0.013438  0.207300
FTM  -0.132869 -0.172241  0.566386  0.000294
FTA  -0.111062 -0.115687  0.425009 -0.007496
FT%   0.013005 -0.054336  0.092512  0.028219
OREB -0.177308  0.426250  0.145973 -0.236630
DREB -0.090709  0.289962  0.054327  0.352772
REB  -0.183751  0.508106  0.132492  0.192153
AST   0.344918  0.114477  0.007494  0.001327
STL   0.021112 -0.059029  0.027040 -0.351298
BLK  -0.032251  0.124372  0.124792  0.027767
TOV  -0.050397 -0.045392  0.251163  0.414176
PF    0.012119  0.032937  0.411367  0.093152

In [ ]:
pca.explained_variance_

array([0.08455887, 0.06150172, 0.04412148, 0.04070394])

In [ ]:
pca.explained_variance_ratio_

array([0.20267175, 0.14740809, 0.1057509 , 0.09755972])

In [ ]:
scaler.fit(prcomp)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [ ]:
scaled_pca = scaler.transform(prcomp)

In [ ]:
scaled_pca = pd.DataFrame(data = scaled_pca)

In [ ]:
scaled = scaled_pca

In [ ]:
def elbow(X):
    sse = []
    
    for i in range(1,11):
        km = KMeans(n_clusters=i)
        km.fit(X)
        sse.append(km.inertia_)
        
    fig = px.line(sse)
    fig.show()
    
elbow(scaled)

In [ ]:
km = KMeans(n_clusters=3).fit(scaled)

In [ ]:
km.cluster_centers_

array([[0.45033281, 0.51212878, 0.35689804, 0.35206067],
       [0.65626749, 0.4069602 , 0.3552276 , 0.53703919],
       [0.37493934, 0.34625471, 0.38753269, 0.55837288]])

In [ ]:
predict = pd.DataFrame(km.predict(scaled))

In [ ]:
predict.columns = ['predict']

In [ ]:
scaled = pd.DataFrame(data=scaled)

In [ ]:
r = pd.concat([scaled, predict], axis=1)

In [ ]:
result = r

In [ ]:
result.columns = ['득점률', '적극성', '수비기술', '3점슛', 'Cluster', 'TEAM']

In [ ]:
result['TEAM'] = ''
result['TEAM'] = data['TEAM']

In [ ]:
result

득점률       적극성      수비기술       3점슛  Cluster TEAM
0     0.497788  0.329404  0.341240  0.270128        0  MIN
1     0.584498  0.535535  0.367330  0.714144        1  LAL
2     0.614646  0.314959  0.292218  0.460848        1  NYK
3     0.699366  0.488216  0.276537  0.498095        1  DET
4     0.319448  0.822754  0.330173  0.306565        0  BOS
...        ...       ...       ...       ...      ...  ...
1225  0.350237  0.228174  0.496272  0.565188        2  MIL
1226  0.417529  0.493708  0.209980  0.281262        0  DET
1227  0.657163  0.630706  0.693242  0.198966        0  IND
1228  0.237583  0.393974  0.479196  0.586602        2  CLE
1229  0.670643  0.550971  0.266069  0.427464        1  HOU

[1230 rows x 6 columns]

In [ ]:
HOU = result[result['TEAM']=='HOU']

In [ ]:
HOU = HOU.mean()

In [ ]:
HOU.values

array([0.53307852, 0.43016853, 0.34967646, 0.61251174, 1.30769231])

In [ ]:
temp = pd.DataFrame(HOU)

In [ ]:
temp.values

array([[0.53307852],
       [0.43016853],
       [0.34967646],
       [0.61251174],
       [1.30769231]])

In [ ]:
HOU = pd.DataFrame(data=[[0.53307852, 0.43016853, 0.34967646, 0.61251174],
                        ],columns=['PCA1','PCA2','PCA3','PCA4'])

In [ ]:
HOU

PCA1      PCA2      PCA3      PCA4
0  0.533079  0.430169  0.349676  0.612512

In [ ]:
c_result = km.cluster_centers_

In [ ]:
c_result = pd.DataFrame(data=c_result)

In [ ]:
c_result.columns = ['PCA1','PCA2','PCA3','PCA4']

In [ ]:
c_result.values[0]

array([0.45033281, 0.51212878, 0.35689804, 0.35206067])

In [ ]:
c_result

PCA1      PCA2      PCA3      PCA4
0  0.450333  0.512129  0.356898  0.352061
1  0.656267  0.406960  0.355228  0.537039
2  0.374939  0.346255  0.387533  0.558373

In [ ]:
categories = ['득점률','적극성','수비기술','3점슛']

fig = go.Figure()

fig.add_trace(go.Scatterpolar(
    r = c_result.values[0],
    theta = categories,
    fill='toself',
    name='적극돌파형'
))

fig.add_trace(go.Scatterpolar(
    r = c_result.values[1],
    theta = categories,
    fill='toself',
    name='다재다능형'
))

fig.add_trace(go.Scatterpolar(
    r = c_result.values[2],
    theta = categories,
    fill='toself',
    name='강한수비_3점슈터형'
))

fig.add_trace(go.Scatterpolar(
    r = HOU.values[0],
    theta = categories,
    fill='toself',
    name='HOU'
))

fig.update_layout(
  polar=dict(
    radialaxis=dict(
      visible=True,
      range=[0, 0.7]
    )),
)

fig.show()

In [ ]:
result.columns

Index(['PCA1', 'PCA2', 'PCA3', 'PCA4', 'predict', 'TEAM'], dtype='object')

In [ ]:
pure_res = result[['PCA1', 'PCA2', 'PCA3', 'PCA4', 'TEAM']]

In [ ]:
GSW = pure_res[pure_res['TEAM']=='GSW']

In [ ]:
GSW = GSW.mean()

In [ ]:
GSW.values

array([0.62309412, 0.4282821 , 0.41144514, 0.51022915])

In [ ]:
temp = pd.DataFrame(GSW)

In [ ]:
temp.values

array([[0.62309412],
       [0.4282821 ],
       [0.41144514],
       [0.51022915]])

In [ ]:
GSW = pd.DataFrame(data=[[0.62309412, 0.4282821 , 0.41144514, 0.51022915]],
                  columns=['PCA1','PCA2','PCA3','PCA4'])

In [ ]:
GSW

PCA1      PCA2      PCA3      PCA4
0  0.623094  0.428282  0.411445  0.510229

In [ ]:
categories = ['득점률','적극성','수비기술','3점슛']

fig = go.Figure()

fig.add_trace(go.Scatterpolar(
    r = c_result.values[0],
    theta = categories,
    fill='toself',
    name='적극돌파형'
))

fig.add_trace(go.Scatterpolar(
    r = c_result.values[1],
    theta = categories,
    fill='toself',
    name='다재다능형'
))

fig.add_trace(go.Scatterpolar(
    r = c_result.values[2],
    theta = categories,
    fill='toself',
    name='강한수비_3점슈터형'
))

fig.add_trace(go.Scatterpolar(
    r = GSW.values[0],
    theta = categories,
    fill='toself',
    name='GSW'
))

fig.update_layout(
  polar=dict(
    radialaxis=dict(
      visible=True,
      range=[0, 0.7]
    )),
)

fig.show()

In [ ]:
result.columns

Index(['PCA1', 'PCA2', 'PCA3', 'PCA4', 'predict', 'TEAM'], dtype='object')

In [ ]:
pure_res = result[['PCA1', 'PCA2', 'PCA3', 'PCA4', 'TEAM']]

In [ ]:
POR = pure_res[pure_res['TEAM']=='POR']

In [ ]:
POR = POR.mean()

In [ ]:
POR.values

array([0.43577952, 0.43873472, 0.36086848, 0.51569908])

In [ ]:
POR = pd.DataFrame(data=[[0.43577952, 0.43873472, 0.36086848, 0.51569908]],
                  columns=['PCA1','PCA2','PCA3','PCA4'])

In [ ]:
POR

PCA1      PCA2      PCA3      PCA4
0  0.43578  0.438735  0.360868  0.515699

In [ ]:
categories = ['득점률','적극성','수비기술','3점슛']

fig = go.Figure()

fig.add_trace(go.Scatterpolar(
    r = c_result.values[0],
    theta = categories,
    fill='toself',
    name='적극돌파형'
))

fig.add_trace(go.Scatterpolar(
    r = c_result.values[1],
    theta = categories,
    fill='toself',
    name='다재다능형'
))

fig.add_trace(go.Scatterpolar(
    r = c_result.values[2],
    theta = categories,
    fill='toself',
    name='강한수비_3점슈터형'
))

fig.add_trace(go.Scatterpolar(
    r = POR.values[0],
    theta = categories,
    fill='toself',
    name='POR'
))

fig.update_layout(
  polar=dict(
    radialaxis=dict(
      visible=True,
      range=[0, 0.7]
    )),
)

fig.show()

In [ ]:
result.columns

Index(['PCA1', 'PCA2', 'PCA3', 'PCA4', 'predict', 'TEAM'], dtype='object')

In [ ]:
pure_res = result[['PCA1', 'PCA2', 'PCA3', 'PCA4', 'TEAM']]

In [ ]:
comp = pure_res[pure_res['TEAM']=='DAL']

In [ ]:
comp = comp.mean()

In [ ]:
comp.values

array([0.52023354, 0.38663803, 0.27680306, 0.53699852])

In [ ]:
comp = pd.DataFrame(data=[[0.52023354, 0.38663803, 0.27680306, 0.53699852]],
                  columns=['PCA1','PCA2','PCA3','PCA4'])

In [ ]:
comp

PCA1      PCA2      PCA3      PCA4
0  0.520234  0.386638  0.276803  0.536999

In [ ]:
categories = ['득점률','적극성','수비기술','3점슛']

fig = go.Figure()

fig.add_trace(go.Scatterpolar(
    r = c_result.values[0],
    theta = categories,
    fill='toself',
    name='적극돌파형'
))

fig.add_trace(go.Scatterpolar(
    r = c_result.values[1],
    theta = categories,
    fill='toself',
    name='다재다능형'
))

fig.add_trace(go.Scatterpolar(
    r = c_result.values[2],
    theta = categories,
    fill='toself',
    name='강한수비_3점슈터형'
))

fig.add_trace(go.Scatterpolar(
    r = comp.values[0],
    theta = categories,
    fill='toself',
    name='DAL'
))

fig.update_layout(
  polar=dict(
    radialaxis=dict(
      visible=True,
      range=[0, 0.7]
    )),
)

fig.show()